title: Ashvin Ganesan # your name (or website title) here
logo: "/images/ashvin_headshot_circular.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Computer Science & Mathematics student at RPI with experience in AI/ML, software engineering, and robotics. 
  <br><br>
  <strong>Navigation:</strong> <a href="/experience">Experience</a> | <a href="/projects">Projects</a> | <a href="/skills">Skills</a> | <a href="/pdf/Ashvin_Ganesan_Resume_MAY_2025.pdf" download>Resume (PDF)</a>
  <br><br>
  <a href="https://github.com/ashvinganesan">GitHub</a> | 
  <a href="https://www.linkedin.com/in/ashvin-ganesan/">LinkedIn</a> | 
  <a href="mailto:ashvin.ganesan@gmail.com">Email</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - LICENSE
